### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by john-yick** [SouthbankSoftware/provendb-sdk-node#4]
Looks like the SSL Certificate for the endpoint has expired for the target endpoint

 Error: 14 UNAVAILABLE: upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
      at callErrorFromStatus (node_modules/@grpc/grpc-js/build/src/call.js:31:19)
      at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client.js:192:76)
      at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
      at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)

**Comment by gharriso** [comment]
While taking a look at this, I noticed that while everything worked OK on my old setup, when I my Axios version I started getting the same error.  Not sure if that means that the error is with Axios or the certificate (which seems valid). 

Are you using Axios my any chance?  Can you share your connection code?  Ta!

**Comment by john-yick** [comment]
So I can provide a snippet of the code:

```
module.exports.submitProof = async (payload) => {
  // Create a new anchor client using your credentials
  const client = anchor.connect(
    anchor.withCredentials(config.get("provendb.credentials"))
  );
  const hash = this.calculateHash(payload);

  const proof = await client.submitProof(
    hash,
    anchor.submitProofWithAnchorType(anchor.Anchor.Type.ETH),
    anchor.submitProofWithAwaitConfirmed(true)
  );

  logger.info(
    `[${payload.sessionUserId}][${payload.documentId}] Proof calculated: ${proof.hash}`
  );

  return proof;
};
```

The axios version that my code uses for other aspects of the code is 0.27.2

Thanks

**Comment by gharriso** [comment]
Sorry about that.  Please try it now, it should be resolved.

**Comment by john-yick** [comment]
@gharriso thank you for resolving can confirmed the fix works 👍
